  # Backend API
  backend:
    build: ./backend
    environment:
     DATABASE_URL: mysql://albarkahospital:tacheyon5567@localhost:3306/albarkahospital
     DB_NAME: albarkahospital
     DB_PORT: 3306
     DB_HOST: localhost
     DB_PASS: tacheyon5567
     DB_USER: albarkahospital
     SECRET: albarkahospitalwawa777
    ports:
      - "8000:8000"
    volumes:
      - ./backend/backup:/app/backup  # For file uploads
    restart: unless-stopped

  # Frontend
  frontend:
    build: ./frontend
    environment:
     NEXT_PUBLIC_SERVER_API: http://localhost:8000
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped
