import express from "express";
import { config } from "dotenv";
import cors from "cors";
import accounts from "./routes/accounts.js";
import auth from "./routes/auth.js";
import backup from "./routes/backup.js";
import report from "./routes/report.js";
import settings from "./routes/settings.js";
import patients from "./routes/patients.js";
import encounters from "./routes/encounters.js";
import drugsInventory from "./routes/drugsInventory.js";
import transactions from "./routes/transactions.js";
import { verifyToken } from "./middlewares/jwt.js";
const app = express();
const port = 8000;
config();
app.use(express.json());
app.use(cors());
app.use("/auth", auth);
app.use("/backup", backup);
app.use("/accounts", verifyToken, accounts);
app.use("/reports", verifyToken, report);
app.use("/patients", verifyToken, patients);
app.use("/transactions", verifyToken, transactions);
app.use("/encounters", verifyToken, encounters);
app.use("/drugsinventory", verifyToken, drugsInventory);
app.use("/settings", verifyToken, settings);
app.get("/", (req, res) => {
	res.send("<h2>Welcome</h2>");
});
app.listen(port, () => {
	console.log(`Albarka server listening on port ${port}`);
});
